# Generated by Django 4.2.1 on 2023-06-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='AddedBy',
        ),
        migrations.RemoveField(
            model_name='companyhotelrate',
            name='AddedBy',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='AddedBy',
        ),
        migrations.RemoveField(
            model_name='hotelrate',
            name='AddedBy',
        ),
    ]
