# Generated by Django 4.2.1 on 2023-06-02 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0006_company_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyHotelRate',
        ),
    ]
