# Generated by Django 4.2.1 on 2023-06-02 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0007_delete_companyhotelrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelrate',
            name='HotelName',
        ),
        migrations.CreateModel(
            name='CompanyHotelRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotation.company')),
                ('RateType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotation.hotelrate')),
            ],
        ),
        migrations.AddField(
            model_name='hotelrate',
            name='HotelName',
            field=models.ManyToManyField(to='quotation.hotel'),
        ),
    ]
