# Generated by Django 4.2.1 on 2023-06-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0009_rename_companydescription_company_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_added',
            field=models.DateTimeField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, max_length=200, null=True),
        ),
    ]
