# Generated by Django 4.2.1 on 2023-06-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0010_employee_date_added_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelrate',
            name='company_applicable_to',
            field=models.ManyToManyField(to='quotation.company'),
        ),
    ]
