# Generated by Django 4.2.1 on 2023-06-03 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0011_hotelrate_company_applicable_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelrate',
            name='hotel_name',
        ),
        migrations.AddField(
            model_name='hotelrate',
            name='hotel_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='quotation.hotel'),
            preserve_default=False,
        ),
    ]
