# Generated by Django 4.2.1 on 2023-06-03 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0012_remove_hotelrate_hotel_name_hotelrate_hotel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationMainRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, max_length=200, null=True)),
                ('date_to', models.DateField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, choices=[('Kenya', 'Kenya')], max_length=200)),
                ('destination', models.CharField(blank=True, choices=[('Samburu', 'Samburu'), ('Mara', 'Mara'), ('L. Nakuru', 'L. Nakuru')], max_length=200)),
                ('number_adult_citizen', models.IntegerField(blank=True, default=0, null=True)),
                ('number_adult_resident', models.IntegerField(blank=True, default=0, null=True)),
                ('number_adult_nonresident', models.IntegerField(blank=True, default=0, null=True)),
                ('number_child_citizen', models.IntegerField(default=0, null=True)),
                ('number_child_resident', models.IntegerField(default=0, null=True)),
                ('number_child_nonresident', models.IntegerField(default=0, null=True)),
                ('quotation_id', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('date_added', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='username',
        ),
        migrations.AlterField(
            model_name='company',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hotelrate',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='QuotationRoomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_rooms_for_category_type', models.IntegerField(default=1, null=True)),
                ('no_of_adults_sharing', models.IntegerField(default=1, null=True)),
                ('no_of_old_children_sharing', models.IntegerField(default=0, null=True)),
                ('no_of_young_children_sharing', models.IntegerField(default=0, null=True)),
                ('unique_id', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('quotation_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotation.quotationmainrequest')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_category_requests', to='quotation.hotelrate')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_type_requests', to='quotation.hotelrate')),
            ],
        ),
        migrations.AddField(
            model_name='quotationmainrequest',
            name='hotel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotation.hotel'),
        ),
    ]
