# Generated by Django 4.2.1 on 2023-06-03 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0013_quotationmainrequest_remove_hotel_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationmainrequest',
            name='destination',
        ),
        migrations.AddField(
            model_name='quotationmainrequest',
            name='area',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='main_request_area', to='quotation.hotel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotationmainrequest',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_request_country', to='quotation.hotel'),
        ),
        migrations.AlterField(
            model_name='quotationmainrequest',
            name='hotel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_request_hotel', to='quotation.hotel'),
        ),
    ]
