# Generated by Django 4.2.1 on 2023-06-03 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0015_quotationroomrequest_package_type'),
    ]

    operations = [
        
    ]
