# Generated by Django 4.2.1 on 2023-06-03 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0018_alter_hotel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='username',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='quotation.employee'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quotation.employee'),
        ),
    ]
