# Generated by Django 4.2.1 on 2023-06-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0019_alter_company_username_alter_hotel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationmainrequest',
            name='area',
        ),
        migrations.RemoveField(
            model_name='quotationmainrequest',
            name='country',
        ),
        migrations.RemoveField(
            model_name='quotationroomrequest',
            name='room_category',
        ),
        migrations.RemoveField(
            model_name='quotationroomrequest',
            name='room_type',
        ),
    ]
