# Generated by Django 4.2.1 on 2023-06-06 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0022_remove_quotationroomrequest_no_of_adults_single'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='username',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='quotation.employee'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hotels', to='quotation.employee'),
        ),
    ]
