# Generated by Django 4.2.1 on 2023-06-06 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0023_alter_company_username_alter_hotel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='username',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='username',
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='quotation.company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='quotation.hotel'),
        ),
    ]
