# Generated by Django 4.2.1 on 2023-06-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0025_company_company_footer_company_company_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelrate',
            name='package_type',
            field=models.CharField(blank=True, choices=[('FB Accomodation Only', 'FB Accomodation Only'), ('All inc', 'all inclusive'), ('Ground', 'Ground'), ('Air', 'Air'), ('Half Board', 'Half Board'), ('Bed & Breakfast', 'Bed & Breakfast')], max_length=200),
        ),
    ]
