# Generated by Django 4.2.1 on 2023-06-18 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0026_alter_hotelrate_package_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp for creation of this record', verbose_name='date_created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp for latest update of this record', verbose_name='date_updated'),
        ),
    ]
