# Generated by Django 4.2.1 on 2023-06-18 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0027_remove_employee_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='company',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='hotelrate',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='hotelrate',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='quotationmainrequest',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='quotationmainrequest',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='company',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp for creation of this record', verbose_name='date_created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp for latest update of this record', verbose_name='date_updated'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp for creation of this record', verbose_name='date_created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp for latest update of this record', verbose_name='date_updated'),
        ),
        migrations.AddField(
            model_name='hotelrate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp for creation of this record', verbose_name='date_created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelrate',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp for latest update of this record', verbose_name='date_updated'),
        ),
        migrations.AddField(
            model_name='quotationmainrequest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp for creation of this record', verbose_name='date_created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationmainrequest',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp for latest update of this record', verbose_name='date_updated'),
        ),
        migrations.AddField(
            model_name='quotationroomrequest',
            name='no_of_children_sharing',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
