# Generated by Django 4.2.1 on 2023-06-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0029_remove_quotationmainrequest_number_adult_citizen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationmainrequest',
            name='area',
            field=models.CharField(default='Mara', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationmainrequest',
            name='country',
            field=models.CharField(default='Kenya', max_length=255),
            preserve_default=False,
        ),
    ]
