# Generated by Django 4.2.1 on 2023-06-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0033_remove_quotationroomrequest_error_msg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('G', 'Generating'), ('R', 'Ready'), ('E', 'Error')], default='P', max_length=2)),
                ('error_msg', models.CharField(blank=True, max_length=128, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs')),
            ],
        ),
    ]
