# Generated by Django 4.2.1 on 2023-06-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0034_pagerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageRequest',
        ),
        migrations.RemoveField(
            model_name='quotationmainrequest',
            name='error_msg',
        ),
        migrations.RemoveField(
            model_name='quotationmainrequest',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='quotationmainrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='quotationmainrequest',
            name='url',
        ),
    ]
