# Generated by Django 3.1.7 on 2023-06-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0035_delete_pagerequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationroomrequest',
            name='unique_id',
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hotelrate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quotationmainrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quotationroomrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quotationroomrequest',
            name='package_type',
            field=models.CharField(blank=True, choices=[('FB Accomodation Only', 'FB Accomodation Only'), ('All inc', 'all inclusive'), ('Ground', 'Ground'), ('Air', 'Air'), ('Half Board', 'Half Board'), ('Bed & Breakfast', 'Bed & Breakfast')], max_length=200),
        ),
    ]
